name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-**'

jobs:
  release-github:
    name: release for all platforms
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.6'

      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: '1.23.0'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-dockerhub:
    name: publish docker image on docker hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/waster:${{ github.ref_name }} , ${{ secrets.DOCKER_HUB_USERNAME }}/waster:latest
          file: ./deployments/docker-image/dockerfile
          build-args: GO_VERSION=${{ vars.GO_VERSION }}
